### ISSUE TITLE
Career portal applicants receive 'candidate ownership change' email in error

### ISSUE THREAD

**Issue by RussH** [opencats/OpenCATS#343]
reported in the forums; http://forums.opencats.org/viewtopic.php?f=4&t=977
Issue: Even when no emails are checked to send, the applicant still gets an email message:

From: email@ofadmin.com
Subject:CATS Notification: Candidate Ownership Change
Body: email@ofapplicant.com
Powered by CATS (Free ATS)

Workaround: commented out the following in lib/Candidates.php
```
if (!empty($emailAddress))
        {
            /* Send e-mail notification. */
            //FIXME: Make subject configurable.
            // $mailer = new Mailer($this->_siteID);
            // $mailerStatus = $mailer->sendToOne(
            //    array($emailAddress, ''),
            //    'CATS Notification: Candidate Ownership Change',
            //    $email,
            //    true
            //);
        }
```

**Comment by evank28** [comment]
@RussH Why is this labelled as NotAnIssue? seems like a very easy fix. Can I submit a PR?

**Comment by RussH** [comment]
HI @evank28  this is flagged as not an issue as it's only been reported once, may be down to user misconfiguration and there's a simple workaround posted above. If this is reported by multiple users then a PR to change default behaviour would be accepted

**Comment by mattpr** [comment]
OpenCATS 0.11.0.

Submit test job application with questionnaire.

Candidate (not recruiter) receives 2 emails.

1) "CATS Notification: Candidate Ownership Change" with message body that contains ONLY the candidate's email address.
2) Thank You for Your Application 

https://github.com/opencats/OpenCATS/blob/v0.11.0/lib/Candidates.php#L363

Recruiter receives 1 email at the same time with subject: "CATS - A Candidate Has Applied to Your Job Order".

It looks like there was a [related fix](https://github.com/opencats/opencats/issues/725) in March by @anonymoususer72041... but this fixed a different issue (arg misalignment) in a different call to `Candidates->update` where `$email` and `$emailAddress` are set to empty string.

[This call](https://github.com/opencats/OpenCATS/blob/v0.11.0/modules/careers/CareersUI.php#L381) from `modules/careers/CareersUI.php` to `Candidates->update` sets `$email` and `$emailAddress` to `$email1` (the candidate's email).  This triggers the spurious email to the candidate.

**Comment by mattpr** [comment]
@RussH -- (mentioning you just in case you didn't get a notification from this old issue).  

I think I tracked down the source of this spurious email bug (see last line in my previous comment) but am not sure the intent of the $email and $emailAddress parameters (candidate owner users?) passed to Candidates->update (vs email1, email2)...so I can't say for sure.  Just wanted to make sure you saw it.

**Comment by RussH** [comment]
Thanks — we'll get this incorrect email to candidates resolved.

**Comment by mattpr** [comment]
Hi @RussH, 

Testing again with 0.11.1.

The spurius email is still there.  

Printed a stacktrace in Candidates->update to track down the responsible caller:

```
#0 /opt/apps/opencats/opencats-v0.11.1/lib/Questionnaire.php(644): Candidates->update('...', true, '...', '', '...', '...', '', '', '', '', '', '', '...', '...', '...', '', '', NULL, '', false, '', '', '', '', '...', '...', false, '...', '...')
#1 /opt/apps/opencats/opencats-v0.11.1/modules/careers/CareersUI.php(1781): Questionnaire->doActions('...', 4, Array)
#2 /opt/apps/opencats/opencats-v0.11.1/modules/careers/CareersUI.php(857): CareersUI->onApplyToJobOrder(4)
#3 /opt/apps/opencats/opencats-v0.11.1/modules/careers/CareersUI.php(67): CareersUI->careersPage()
#4 /opt/apps/opencats/opencats-v0.11.1/lib/ModuleUtility.php(79): CareersUI->handleRequest()
#5 /opt/apps/opencats/opencats-v0.11.1/index.php(195): ModuleUtility::loadModule('...')
#6 /opt/apps/opencats/opencats-v0.11.0/careers/index.php(39): include_once('...')
```

The issue is coming from `Questionnaire->doActions` where [there is also a call](https://github.com/opencats/OpenCATS/blob/v0.11.1/lib/Questionnaire.php#L672) to `Candidates->update` with `$email1` passed in the wrong spot again.

**I also noticed** something odd in the stack trace above unrelated to this issue.

Note that `#6` is in the `v0.11.0` release directory whereas `#5` is in the `v0.11.1` release directory?

`careers/index.php(39)`: `include_once(CATSUtility::getIndexName());`

Directory structure looks like this:

```
root@ats:/opt/apps/opencats# ls -lha
total 15M
drwxr-xr-x  6 root     root     4.0K Sep  4 11:24 .
drwxr-xr-x  3 root     root     4.0K Aug 23 11:43 ..
lrwxrwxrwx  1 root     root       35 Sep  3 13:30 current -> /opt/apps/opencats/opencats-v0.11.1
drwxrwsr-x 20 www-data www-data 4.0K Aug 31 08:11 opencats-v0.10.0
-rw-r-----  1 root     root     3.0M Aug 23 11:53 opencats-v0.10.0.zip
drwxrwsr-x 20 www-data www-data 4.0K Aug 31 12:38 opencats-v0.11.0
-rw-r--r--  1 root     root     2.9M Aug 31 08:15 opencats-v0.11.0.zip
drwxrwsr-x 24 www-data www-data 4.0K Sep  4 11:29 opencats-v0.11.1
drwxrwsr-x 20 www-data www-data 4.0K Sep  3 13:39 opencats-v0.11.1-full
-rw-r--r--  1 root     root     5.6M Sep  3 13:30 opencats-v0.11.1-full.tar.gz
-rw-r--r--  1 root     root     2.6M Sep  4 11:24 opencats-v0.11.1.tar.gz
```

web root is `/opt/apps/opencats/current`.  Maybe some bug with php8.5-fpm in how it resolves paths for includes (e.g. resolving symlinks and caching non-symlink paths).
