### ISSUE TITLE
Not able to see the Candidate Records and other Records like Job Orders, Companies and Contacts

### ISSUE THREAD

**Issue by KamalJoshiDelhi** [opencats/OpenCATS#428]
Hi
 I upgraded the Opencats to 0.9.4-2 and now I am not able to see details of any Candidate, any Job Order, any Company or any Contact when I click on any of them... for example on clicking a candidate name when I want to see his records, It shows me something like the following screen
![image](https://user-images.githubusercontent.com/22269742/56269477-6185ae80-6111-11e9-891d-b25e90b7703a.png)

In a similar way it shows the records for Job Order or for Client Company or for Contacts... What is it that I need to change to solve this???

**Comment by KamalJoshiDelhi** [comment]
Here is the error log for the above issue, if someone can suggest to me what can be done to avoid it please????
===========================
[17-Apr-2019 08:43:03 Etc/GMT] PHP Warning:  include_once(./vendor/autoload.php): failed to open stream: No such file or directory in /home/mywebserver/public_html/ats/lib/TemplateUtility.php on line 38
[17-Apr-2019 08:43:03 Etc/GMT] PHP Warning:  include_once(): Failed opening './vendor/autoload.php' for inclusion (include_path='.:/opt/alt/php71/usr/share/pear') in /home/mywebserver/public_html/ats/lib/TemplateUtility.php on line 38
[17-Apr-2019 08:43:03 Etc/GMT] PHP Warning:  include_once(./vendor/autoload.php): failed to open stream: No such file or directory in /home/mywebserver/public_html/ats/lib/Companies.php on line 2
[17-Apr-2019 08:43:03 Etc/GMT] PHP Warning:  include_once(): Failed opening './vendor/autoload.php' for inclusion (include_path='.:/opt/alt/php71/usr/share/pear') in /home/mywebserver/public_html/ats/lib/Companies.php on line 2
[17-Apr-2019 08:43:03 Etc/GMT] PHP Warning:  include_once(./vendor/autoload.php): failed to open stream: No such file or directory in /home/mywebserver/public_html/ats/lib/JobOrders.php on line 2
[17-Apr-2019 08:43:03 Etc/GMT] PHP Warning:  include_once(): Failed opening './vendor/autoload.php' for inclusion (include_path='.:/opt/alt/php71/usr/share/pear') in /home/mywebserver/public_html/ats/lib/JobOrders.php on line 2
[17-Apr-2019 08:43:03 Etc/GMT] PHP Warning:  include_once(./vendor/autoload.php): failed to open stream: No such file or directory in /home/mywebserver/public_html/ats/modules/candidates/Show.tpl on line 2
[17-Apr-2019 08:43:03 Etc/GMT] PHP Warning:  include_once(): Failed opening './vendor/autoload.php' for inclusion (include_path='.:/opt/alt/php71/usr/share/pear') in /home/mywebserver/public_html/ats/modules/candidates/Show.tpl on line 2
[17-Apr-2019 08:43:03 Etc/GMT] PHP Fatal error:  Uncaught Error: Class 'OpenCATS\UI\CandidateQuickActionMenu' not found in /home/mywebserver/public_html/ats/modules/candidates/Show.tpl:56
Stack trace:
#0 /home/mywebserver/public_html/ats/lib/Template.php(115): include()
#1 /home/mywebserver/public_html/ats/modules/candidates/CandidatesUI.php(694): Template->display(NULL)
#2 /home/mywebserver/public_html/ats/modules/candidates/CandidatesUI.php(92): CandidatesUI->show()
#3 /home/mywebserver/public_html/ats/lib/ModuleUtility.php(79): CandidatesUI->handleRequest()
#4 /home/mywebserver/public_html/ats/index.php(268): ModuleUtility::loadModule('candidates')
#5 {main}
  thrown in /home/mywebserver/public_html/ats/modules/candidates/Show.tpl on line 56 
================================

**Comment by RussH** [comment]
Sounds as though you haven't downloaded 'full' you've downloaded the standard docker image and therefore need to run composer to get the dependencies installed. 

1. install composer from getcomposer.org
2. run `composer install` in the webroot of opencats.
3. Check or change the file ownership of the new files so they're owned by the user running Apache (normally sudo chown -r  www-data:www-data /var/www/html/opencats)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by KamalJoshiDelhi** [comment]
When I download composer.exe file from getcomposer.org 
how can I run this exe file on my webserver through a control panel???

**Comment by KamalJoshiDelhi** [comment]
I remembered last time Alain Maisonneuve took over my system and used putty to do something like this... I searched for it and was able to run Composer on my opencats webroot... I could do it successfully but am still not able to view any of the details.... :(

**Comment by RussH** [comment]
Okay you're running php 7.1. The Current release only supports php 5.x

The development branch does support php 7.x but it's not released yet (still testing).

Please change your config to use php 5.6

**Comment by KamalJoshiDelhi** [comment]
I was running my last opencat version also on php7 and that time it was all working fine...

**Comment by KamalJoshiDelhi** [comment]
I changed my php version back to 5.6 just to check if it works fine... It was still the same... could not see the Single candidate information with the following logged in the error log...
------------------------------------------
[17-Apr-2019 16:40:23 Etc/GMT] PHP Warning:  include_once(./vendor/autoload.php): failed to open stream: No such file or directory in /home/mywebserver/public_html/ats/lib/TemplateUtility.php on line 38
[17-Apr-2019 16:40:23 Etc/GMT] PHP Warning:  include_once(): Failed opening './vendor/autoload.php' for inclusion (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/mywebserver/public_html/ats/lib/TemplateUtility.php on line 38
[17-Apr-2019 16:40:24 Etc/GMT] PHP Warning:  include_once(./vendor/autoload.php): failed to open stream: No such file or directory in /home/mywebserver/public_html/ats/lib/Companies.php on line 2
[17-Apr-2019 16:40:24 Etc/GMT] PHP Warning:  include_once(): Failed opening './vendor/autoload.php' for inclusion (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/mywebserver/public_html/ats/lib/Companies.php on line 2
[17-Apr-2019 16:40:24 Etc/GMT] PHP Warning:  include_once(./vendor/autoload.php): failed to open stream: No such file or directory in /home/mywebserver/public_html/ats/lib/JobOrders.php on line 2
[17-Apr-2019 16:40:24 Etc/GMT] PHP Warning:  include_once(): Failed opening './vendor/autoload.php' for inclusion (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/mywebserver/public_html/ats/lib/JobOrders.php on line 2
[17-Apr-2019 16:40:24 Etc/GMT] PHP Warning:  include_once(./vendor/autoload.php): failed to open stream: No such file or directory in /home/mywebserver/public_html/ats/modules/candidates/Show.tpl on line 2
[17-Apr-2019 16:40:24 Etc/GMT] PHP Warning:  include_once(): Failed opening './vendor/autoload.php' for inclusion (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/mywebserver/public_html/ats/modules/candidates/Show.tpl on line 2
[17-Apr-2019 16:40:24 Etc/GMT] PHP Fatal error:  Class 'OpenCATS\UI\CandidateQuickActionMenu' not found in /home/mywebserver/public_html/ats/modules/candidates/Show.tpl on line 56
[17-Apr-2019 16:40:38 Etc/GMT] PHP Warning:  include_once(./vendor/autoload.php): failed to open stream: No such file or directory in /home/mywebserver/public_html/ats/lib/TemplateUtility.php on line 38
[17-Apr-2019 16:40:38 Etc/GMT] PHP Warning:  include_once(): Failed opening './vendor/autoload.php' for inclusion (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/mywebserver/public_html/ats/lib/TemplateUtility.php on line 38
[17-Apr-2019 16:40:39 Etc/GMT] PHP Warning:  include_once(./vendor/autoload.php): failed to open stream: No such file or directory in /home/mywebserver/public_html/ats/lib/Companies.php on line 2
[17-Apr-2019 16:40:39 Etc/GMT] PHP Warning:  include_once(): Failed opening './vendor/autoload.php' for inclusion (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/mywebserver/public_html/ats/lib/Companies.php on line 2
[17-Apr-2019 16:40:39 Etc/GMT] PHP Warning:  include_once(./vendor/autoload.php): failed to open stream: No such file or directory in /home/mywebserver/public_html/ats/lib/JobOrders.php on line 2
[17-Apr-2019 16:40:39 Etc/GMT] PHP Warning:  include_once(): Failed opening './vendor/autoload.php' for inclusion (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/mywebserver/public_html/ats/lib/JobOrders.php on line 2
[17-Apr-2019 16:40:39 Etc/GMT] PHP Warning:  include_once(./vendor/autoload.php): failed to open stream: No such file or directory in /home/mywebserver/public_html/ats/lib/TemplateUtility.php on line 38
[17-Apr-2019 16:40:39 Etc/GMT] PHP Warning:  include_once(): Failed opening './vendor/autoload.php' for inclusion (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/mywebserver/public_html/ats/lib/TemplateUtility.php on line 38
[17-Apr-2019 16:40:39 Etc/GMT] PHP Warning:  include_once(./vendor/autoload.php): failed to open stream: No such file or directory in /home/mywebserver/public_html/ats/lib/Companies.php on line 2
[17-Apr-2019 16:40:39 Etc/GMT] PHP Warning:  include_once(): Failed opening './vendor/autoload.php' for inclusion (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/mywebserver/public_html/ats/lib/Companies.php on line 2
[17-Apr-2019 16:40:39 Etc/GMT] PHP Warning:  include_once(./vendor/autoload.php): failed to open stream: No such file or directory in /home/mywebserver/public_html/ats/lib/JobOrders.php on line 2
[17-Apr-2019 16:40:39 Etc/GMT] PHP Warning:  include_once(): Failed opening './vendor/autoload.php' for inclusion (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/mywebserver/public_html/ats/lib/JobOrders.php on line 2
[17-Apr-2019 16:40:41 Etc/GMT] PHP Warning:  include_once(./vendor/autoload.php): failed to open stream: No such file or directory in /home/mywebserver/public_html/ats/lib/TemplateUtility.php on line 38
[17-Apr-2019 16:40:41 Etc/GMT] PHP Warning:  include_once(): Failed opening './vendor/autoload.php' for inclusion (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/mywebserver/public_html/ats/lib/TemplateUtility.php on line 38
[17-Apr-2019 16:40:41 Etc/GMT] PHP Warning:  include_once(./vendor/autoload.php): failed to open stream: No such file or directory in /home/mywebserver/public_html/ats/lib/Companies.php on line 2
[17-Apr-2019 16:40:41 Etc/GMT] PHP Warning:  include_once(): Failed opening './vendor/autoload.php' for inclusion (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/mywebserver/public_html/ats/lib/Companies.php on line 2
[17-Apr-2019 16:40:41 Etc/GMT] PHP Warning:  include_once(./vendor/autoload.php): failed to open stream: No such file or directory in /home/mywebserver/public_html/ats/lib/JobOrders.php on line 2
[17-Apr-2019 16:40:41 Etc/GMT] PHP Warning:  include_once(): Failed opening './vendor/autoload.php' for inclusion (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/mywebserver/public_html/ats/lib/JobOrders.php on line 2
[17-Apr-2019 16:40:45 Etc/GMT] PHP Warning:  include_once(./vendor/autoload.php): failed to open stream: No such file or directory in /home/mywebserver/public_html/ats/lib/TemplateUtility.php on line 38
[17-Apr-2019 16:40:45 Etc/GMT] PHP Warning:  include_once(): Failed opening './vendor/autoload.php' for inclusion (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/mywebserver/public_html/ats/lib/TemplateUtility.php on line 38
[17-Apr-2019 16:40:45 Etc/GMT] PHP Warning:  include_once(./vendor/autoload.php): failed to open stream: No such file or directory in /home/mywebserver/public_html/ats/lib/Companies.php on line 2
[17-Apr-2019 16:40:45 Etc/GMT] PHP Warning:  include_once(): Failed opening './vendor/autoload.php' for inclusion (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/mywebserver/public_html/ats/lib/Companies.php on line 2
[17-Apr-2019 16:40:45 Etc/GMT] PHP Warning:  include_once(./vendor/autoload.php): failed to open stream: No such file or directory in /home/mywebserver/public_html/ats/lib/JobOrders.php on line 2
[17-Apr-2019 16:40:45 Etc/GMT] PHP Warning:  include_once(): Failed opening './vendor/autoload.php' for inclusion (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/mywebserver/public_html/ats/lib/JobOrders.php on line 2
[17-Apr-2019 16:40:45 Etc/GMT] PHP Warning:  include_once(./vendor/autoload.php): failed to open stream: No such file or directory in /home/mywebserver/public_html/ats/modules/candidates/Show.tpl on line 2
[17-Apr-2019 16:40:45 Etc/GMT] PHP Warning:  include_once(): Failed opening './vendor/autoload.php' for inclusion (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/mywebserver/public_html/ats/modules/candidates/Show.tpl on line 2
[17-Apr-2019 16:40:45 Etc/GMT] PHP Fatal error:  Class 'OpenCATS\UI\CandidateQuickActionMenu' not found in /home/mywebserver/public_html/ats/modules/candidates/Show.tpl on line 56
------------------------------------------

**Comment by KamalJoshiDelhi** [comment]
This issue can be closed as I got my view back on php7.1 by again following your 2nd step i.e. by running 'php composer.phar install command'
Thanks RussH
