### ISSUE TITLE
Sphinx search error

### ISSUE THREAD

**Issue by champakakumara** [opencats/OpenCATS#604]
I Installed Sphinx but when  Search Candidates in opencats got below error,any idea about that?

Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/opencats_index/lib/Search.php on line 2483

Fatal error: Uncaught ArgumentCountError: Too few arguments to function SearchByResumePager::__construct(), 6 passed in /var/www/html/opencats_index/modules/candidates/CandidatesUI.php on line 2088 and exactly 7 expected in /var/www/html/opencats_index/lib/Search.php:2199 Stack trace: #0 /var/www/html/opencats_index/modules/candidates/CandidatesUI.php(2088): SearchByResumePager->__construct(20, 1, '201', 'urban developme...', 'lastName', 'ASC') #1 /var/www/html/opencats_index/modules/candidates/CandidatesUI.php(145): CandidatesUI->onSearch() #2 /var/www/html/opencats_index/lib/ModuleUtility.php(79): CandidatesUI->handleRequest() #3 /var/www/html/opencats_index/index.php(272): ModuleUtility::loadModule('candidates') #4 {main} thrown in /var/www/html/opencats_index/lib/Search.php on line 2199

**Comment by champakakumara** [comment]
yes I followed instructions, but I installed this on Dockerfile, because my opencats run on docker. opencats Version 0.9.6

**Comment by champakakumara** [comment]
/


> Hi @champakakumara can you confirm the version of opencats you've installed, and whether you followed the instructions in https://github.com/opencats/OpenCATS/tree/master/optional-updates/latest-sphinx-search ?

yes I followed instructions, but I installed this on Dockerfile, because my opencats run on docker. opencats Version 0.9.6

**Comment by RussH** [comment]
Let me check that sphinx info - I realise I've not checked the sphinx guidance against PHP 7.2. As a workaround  you may want to check the 'use search on shared hosting' that was made available by @dveos https://forums.opencats.org/viewtopic.php?t=907&hilit=searchd&start=60
