### ISSUE TITLE
OpenCATS not saving Resumes(!)

### ISSUE THREAD

**Issue by zoomiest2** [opencats/OpenCATS#623]
### Expected behavior and actual behavior.
I just installed fresh copy of OpenCATS from Github, and not every application is saving the resume to OpenCATS(!!) Maybe 30% of applications retain the resume.

I e-mailed people, and gave them specific instructions ("click the upload button after you browse for your resume") and from the history, I can see multiple subsequent applications to upload resumes. But still, no resume has been attached.

Is anyone else having this problem?

The sticky issue is that this isn't happening to everyone. it's just SOME applications, but it works for others.

Feedback from Candidates is that they are getting HTTP 500 error

### Steps to reproduce the problem.
People applying for open Job Orders

### What version of opencats are you running? 
Version 0.9.7.2

#### Release or downloaded from Git? 
Git

#### WAMP or LAMP? 
LAMP

### What version of PHP and MySQL are you running
PHP Version 7.2.34-39+ubuntu22.04.1+deb.sury.org+1
MariaDB 10.6.12 

### Attach appropriate error logs. Please attach [apache/mysql] error/access logs as needed.

[Mon Jul 10 11:01:10.680013 2023] [mpm_prefork:notice] [pid 2417] AH00170: caught SIGWINCH, shutting down gracefully
[Mon Jul 10 11:01:10.995425 2023] [mpm_prefork:notice] [pid 2723] AH00163: Apache/2.4.52 (Ubuntu) OpenSSL/3.0.2 configured -- resuming normal operations
[Mon Jul 10 11:01:10.995501 2023] [core:notice] [pid 2723] AH00094: Command line: '/usr/sbin/apache2'
[Mon Jul 10 11:01:16.233258 2023] [mpm_prefork:notice] [pid 2723] AH00170: caught SIGWINCH, shutting down gracefully
[Mon Jul 10 11:01:16.460314 2023] [mpm_prefork:notice] [pid 2742] AH00163: Apache/2.4.52 (Ubuntu) OpenSSL/3.0.2 configured -- resuming normal operations
[Mon Jul 10 11:01:16.460400 2023] [core:notice] [pid 2742] AH00094: Command line: '/usr/sbin/apache2'
[Mon Jul 10 11:03:22.899436 2023] [php7:error] [pid 2743] [client 23.17.234.209:37520] PHP Fatal error:  Uncaught PHPMailer\\PHPMailer\\Exception: Could not instantiate mail function. in /var/www/html/ats/vendor/phpmailer/phpmailer/src/PHPMailer.php:1966\nStack trace:\n#0 /var/www/html/ats/vendor/phpmailer/phpmailer/src/PHPMailer.php(1680): PHPMailer\\PHPMailer\\PHPMailer->mailSend('Date: Mon, 10 J...', '--b1=_3BZuWFf2P...')\n#1 /var/www/html/ats/vendor/phpmailer/phpmailer/src/PHPMailer.php(1516): PHPMailer\\PHPMailer\\PHPMailer->postSend()\n#2 /var/www/html/ats/lib/Mailer.php(241): PHPMailer\\PHPMailer\\PHPMailer->send()\n#3 /var/www/html/ats/lib/Mailer.php(134): Mailer->send(Array, Array, 'CATS - A Candid...', '<img src="https...', true, true, Array, 78, true)\n#4 /var/www/html/ats/lib/CareerPortal.php(466): Mailer->sendToOne(Array, 'CATS - A Candid...', '<img src="https...', true)\n#5 /var/www/html/ats/modules/careers/CareersUI.php(1589): CareerPortalSettings->sendEmail('1250', 'aj@stratosphere...', 'CATS - A Candid...', '<img src="https...')\n#6 /var/www/html/ats/modules/careers/CareersUI.php(750): CareersUI->onApplyToJobOr in /var/www/html/ats/vendor/phpmailer/phpmailer/src/PHPMailer.php on line 1966, referer: https://stratosphere.team/ats/careers/index.php?m=careers&p=onApplyToJobOrder
[Mon Jul 10 11:04:15.928624 2023] [php7:error] [pid 2744] [client 23.17.234.209:43658] PHP Fatal error:  Uncaught PHPMailer\\PHPMailer\\Exception: Could not instantiate mail function. in /var/www/html/ats/vendor/phpmailer/phpmailer/src/PHPMailer.php:1966\nStack trace:\n#0 /var/www/html/ats/vendor/phpmailer/phpmailer/src/PHPMailer.php(1680): PHPMailer\\PHPMailer\\PHPMailer->mailSend('Date: Mon, 10 J...', '--b1=_Nimsizoej...')\n#1 /var/www/html/ats/vendor/phpmailer/phpmailer/src/PHPMailer.php(1516): PHPMailer\\PHPMailer\\PHPMailer->postSend()\n#2 /var/www/html/ats/lib/Mailer.php(241): PHPMailer\\PHPMailer\\PHPMailer->send()\n#3 /var/www/html/ats/lib/Mailer.php(134): Mailer->send(Array, Array, 'CATS - A Candid...', '<img src="https...', true, true, Array, 78, true)\n#4 /var/www/html/ats/lib/CareerPortal.php(466): Mailer->sendToOne(Array, 'CATS - A Candid...', '<img src="https...', true)\n#5 /var/www/html/ats/modules/careers/CareersUI.php(1589): CareerPortalSettings->sendEmail('1250', 'aj@stratosphere...', 'CATS - A Candid...', '<img src="https...')\n#6 /var/www/html/ats/modules/careers/CareersUI.php(750): CareersUI->onApplyToJobOr in /var/www/html/ats/vendor/phpmailer/phpmailer/src/PHPMailer.php on line 1966, referer: https://stratosphere.team/ats/careers/index.php?m=careers&p=onApplyToJobOrder
[Mon Jul 10 11:05:54.095965 2023] [php7:error] [pid 2746] [client 23.17.234.209:42024] PHP Fatal error:  Uncaught PHPMailer\\PHPMailer\\Exception: Could not instantiate mail function. in /var/www/html/ats/vendor/phpmailer/phpmailer/src/PHPMailer.php:1966\nStack trace:\n#0 /var/www/html/ats/vendor/phpmailer/phpmailer/src/PHPMailer.php(1680): PHPMailer\\PHPMailer\\PHPMailer->mailSend('Date: Mon, 10 J...', '--b1=_uN8E7si77...')\n#1 /var/www/html/ats/vendor/phpmailer/phpmailer/src/PHPMailer.php(1516): PHPMailer\\PHPMailer\\PHPMailer->postSend()\n#2 /var/www/html/ats/lib/Mailer.php(241): PHPMailer\\PHPMailer\\PHPMailer->send()\n#3 /var/www/html/ats/lib/Mailer.php(134): Mailer->send(Array, Array, 'CATS - A Candid...', '<img src="https...', true, true, Array, 78, true)\n#4 /var/www/html/ats/lib/CareerPortal.php(466): Mailer->sendToOne(Array, 'CATS - A Candid...', '<img src="https...', true)\n#5 /var/www/html/ats/modules/careers/CareersUI.php(1589): CareerPortalSettings->sendEmail('1250', 'aj@stratosphere...', 'CATS - A Candid...', '<img src="https...')\n#6 /var/www/html/ats/modules/careers/CareersUI.php(750): CareersUI->onApplyToJobOr in /var/www/html/ats/vendor/phpmailer/phpmailer/src/PHPMailer.php on line 1966, referer: https://stratosphere.team/ats/careers/index.php?m=careers&p=onApplyToJobOrder
root@stratosphere:/var/log/apache2# 

EXPLORING A RESOLUTION:
- I downloaded a new clone of the code from github, thinking it was my own instance that had a glitch. Then, I conducted some tests...
- Result: the first test-application went smoothly. I got the "Thanks for applying" page. But, the second and third application tests only gave me the dreaded white screen. I DID, however, have the attachments saved in my database, on two of the tests WITH THE WHITE SCREEN result (both .docx and .pdf). I will have to watch to see if I get any more applications without the resumes... and I will continue to test.

UPDATE:
I just had a software developer candidate drop me a note:

"I found a bug on the job application site, when you click the "send" button, the server sends a response with a status of 500. I found that the problem is in the "LoadTimeData" module, but that's just what I saw from the browser."

**Comment by zoomiest2** [comment]
No progress on this? 
Am I the only one who has this problem?

**Comment by RussH** [comment]
Hi @zoomiest2 there is a whitelist of permitted file formats, if your applicants are using something that's not defined in the whitelist then the file upload will be blocked. The errors you've shared seem to be around the application not finding a working mailserver so probably are unrelated. Can you identify if some particular file format is rejected all the time?

**Comment by RussH** [comment]
@zoomiest2  resolved by PR #820!
